### ISSUE TITLE
hubKV is not defined on @nuxthub/core v0.6.12

### ISSUE THREAD

**Issue by valtlfelipe** [nuxt-hub/core#159]
**Describe the bug**
```
 ERROR  [nuxt] [request error] [unhandled] [500] hubKV is not defined
  at Object.handler (./server/middleware/redirects.ts:8:1)
  at ./node_modules/h3/dist/index.mjs:1962:31
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async Object.callAsync (./node_modules/unctx/dist/index.mjs:72:16)
  at async toNodeHandle (./node_modules/h3/dist/index.mjs:2249:7)
  at async ufetch (./node_modules/unenv/runtime/fetch/index.mjs:9:17)
  at errorhandler (./node_modules/nuxt/dist/core/runtime/nitro/error.js:37:41)
  at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:2256:9)
```

Just using the https://github.com/nuxt-hub/starter template, and running it gives this error above. Looks like it's related with the latest @nuxthub/core v0.6.12, because hard coding 0.6.11 works without any errors.

**Steps to reproduce**
1. Clone https://github.com/nuxt-hub/starter
2. run `npm run dev`
3. Open http://localhost:3000/

**Expected behavior**
To run without that error.

**Comment by farnabaz** [comment]
Should be fixed in https://github.com/nuxt-hub/core/releases/tag/v0.6.13
