### ISSUE TITLE
adding the NuxtHub module give me error with throw createError

### ISSUE THREAD

**Issue by samulefevre** [nuxt-hub/core#201]
bunx nuxi info :
- Operating System: `Darwin`
- Node Version:     `v20.15.1`
- Nuxt Version:     `3.12.3`
- CLI Version:      `3.12.0`
- Nitro Version:    `2.9.7`
- Package Manager:  `bun@1.1.18`
- Builder:          `-`
- User Config:      `compatibilityDate`, `devtools`, `future`, `modules`, `hub`
- Runtime Modules:  `@nuxthub/core@0.7.1`
- Build Modules:    `-`

[nitro] [unhandledRejection] Illegal invocation

  at Object.waitUntil (node_modules/wrangler/wrangler-dist/cli.js:210509:13)
  at H3Event.event.waitUntil (node_modules/nitropack/dist/runtime/app.mjs:96:22)
  at captureError (node_modules/nitropack/dist/runtime/app.mjs:38:23)
  at Object.onError (node_modules/nitropack/dist/runtime/app.mjs:45:7)
  at Server.toNodeHandle (node_modules/h3/dist/index.mjs:2274:27)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Steps to reproduce : 
https://github.com/samulefevre/nuxt-econnrefused
http://localhost:3000/api/test?q=bad

**Comment by farnabaz** [comment]
The issue caused by changes that happen in wrangler `3.64.0` in here https://github.com/cloudflare/workers-sdk/commit/88313e50512ffbcfe8717dc60cf83a4d07a7509d#diff-722ed08e8bf1791f1a733971dfb575012f4129ba13ea6ce0530b70b7f8f18cbe

Freeze wrangler version in `3.63.0` in your `package.json` for now, and you are good to go.

```diff
-    "wrangler": "^3.64.0"  
+    "wrangler": "3.63.0"
```


/cc @Atinux @pi0 This might be something that we should handle in `nitro-cloudflare-dev` package.

**Comment by samulefevre** [comment]
Thank you
