### ISSUE TITLE
bun doesn't work when using "database: true" ?

### ISSUE THREAD

**Issue by mathieunicolas** [nuxt-hub/core#269]
**Describe the bug**
Fresh install with `npx nuxthub init my-app`, I launched the dev server with `bun --bun run dev` and I can see the starter page.

If I add `database: true` in the nuxt.config.ts 

```
hub: {
    database: true
}
```

And launch `bun --bun run dev` again, nothing happens when I go to http://localhost:3000.

Also, when I run `bunx nuxi info`, I have an error about pnpm which I never installed. In my package.json : `  "packageManager": "bun@1.1.27"`
I searched for pnpm in the repo but it's nowhere, just in the README file.

```
 ERROR  Command failed: pnpm --version                                                                                                                                      10:23:56 AM
/bin/sh: pnpm: command not found


  /bin/sh: pnpm: command not found
  
  at checkExecSyncError (node:child_process:890:11)
  at execSync (node:child_process:962:15)
  at getPackageManagerVersion (node_modules/nuxi/dist/shared/nuxi.2014c85a.mjs:23:10)
  at Object.run (node_modules/nuxi/dist/chunks/info.mjs:63:31)
  at runCommand$1 (node_modules/nuxi/dist/shared/nuxi.fefc5017.mjs:1648:26)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.fefc5017.mjs:1639:11)
  at async runMain$1 (node_modules/nuxi/dist/shared/nuxi.fefc5017.mjs:1777:7) 



 ERROR  Command failed: pnpm --version                                                                                                                                      10:23:56 AM
/bin/sh: pnpm: command not found
```

Any idea ? Shall I just switch from bun to pnpm because of something ?

Thanks !

**Comment by atinux** [comment]
Hello,<br><br>I believe it is best to use pnpm.io for now yes

**Comment by mathieunicolas** [comment]
Thanks ! I will do that
