### ISSUE TITLE
v0.8.1 crash without config

### ISSUE THREAD

**Issue by mathix420** [nuxt-hub/core#344]
**Describe the bug**
```
09:55:34.834 [error] [unstorage] [fs] Missing required option `base`.
09:55:34.834   at createError (node_modules/unstorage/drivers/utils/index.mjs:14:15)
09:55:34.834   at createRequiredError (node_modules/unstorage/drivers/utils/index.mjs:24:10)
09:55:34.834   at node_modules/unstorage/drivers/fs.mjs:17:11
09:55:34.834   at useMigrationsStorage (node_modules/@nuxthub/core/dist/runtime/database/server/utils/migrations/helpers.js:5:13)
09:55:34.835   at applyRemoteMigrations (node_modules/@nuxthub/core/dist/runtime/database/server/utils/migrations/remote.js:5:22)
09:55:34.835   at node_modules/@nuxthub/core/dist/module.mjs:429:41
09:55:34.835   at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
09:55:34.835   at async _build (node_modules/nitropack/dist/nitro.mjs:2665:3)
09:55:34.835   at async node_modules/nuxt/dist/index.mjs:3630:5
09:55:34.835   at async build (node_modules/nuxt/dist/index.mjs:5778:3) 
09:55:34.835 
09:55:34.835 [error] [unstorage] [fs] Missing required option `base`.
```

**Steps to reproduce**
1. Use nuxthub 0.8.1
2. Deploy on nuxthub without config

**Expected behavior**
Should work

**Comment by atinux** [comment]
Should be now fixed with [https://github.com/nuxt-hub/core/releases/tag/v0.8.2](https://github.com/nuxt-hub/core/releases/tag/v0.8.2)

Sorry about this!
