### ISSUE TITLE
Can’t upload Team avatar

### ISSUE THREAD

**Issue by stursby** [nuxt-hub/core#36]
I'm trying to upload a Team avatar on `https://admin.hub.nuxt.com/{team_slug}/settings` but it seems to be failing.

Browser Console logs:

```
CflsP016.js:19 TypeError: Cannot read properties of undefined (reading 'files')
    at b (BUc5VUIV.js:1:4417)
    at Sn (CflsP016.js:19:38)
    at Pt (CflsP016.js:19:109)
    at hg (CflsP016.js:19:2180)
    at Proxy.E (C4sbyoA-.js:1:2995)
    at ie.onChange.n.<computed>.n.<computed> (C4sbyoA-.js:1:5228)
    at Sn (CflsP016.js:19:38)
    at Pt (CflsP016.js:19:109)
    at HTMLInputElement.n (CflsP016.js:23:8158)
```

The image I'm trying to upload is only `11kb` so I don't think that's the problem.

**Comment by Atinux** [comment]
Hey @stursby 

Could you tell me what browser you use and upload the image here?
