### ISSUE TITLE
"https://registry.npmjs.org/@nuxthub/core": 404 Not Found

### ISSUE THREAD

**Issue by ziadsarour** [nuxt-hub/core#388]
**Describe the bug**
Cannot install package because it is not published (anymore ?) in npmjs :
https://www.npmjs.com/package/@nuxthub/core

```
npx nuxi module add hub   

 ERROR  [GET] "https://registry.npmjs.org/@nuxthub/core": 404 Not Found           19:17:09

  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async $fetch2 (node_modules/.pnpm/nuxi@3.16.0/node_modules/nuxi/dist/shared/nuxi.014dcc7f.mjs:352:15)
  at async resolveModule (node_modules/.pnpm/nuxi@3.16.0/node_modules/nuxi/dist/chunks/add2.mjs:275:22)
  at async Object.setup (node_modules/.pnpm/nuxi@3.16.0/node_modules/nuxi/dist/chunks/add2.mjs:142:15)
  at async runCommand$1 (node_modules/.pnpm/nuxi@3.16.0/node_modules/nuxi/dist/shared/nuxi.f8a4d1b7.mjs:1620:5)
  at async runCommand$1 (node_modules/.pnpm/nuxi@3.16.0/node_modules/nuxi/dist/shared/nuxi.f8a4d1b7.mjs:1639:11)
  at async runCommand$1 (node_modules/.pnpm/nuxi@3.16.0/node_modules/nuxi/dist/shared/nuxi.f8a4d1b7.mjs:1639:11)
  at async runMain$1 (node_modules/.pnpm/nuxi@3.16.0/node_modules/nuxi/dist/shared/nuxi.f8a4d1b7.mjs:1777:7) 
```

**Steps to reproduce**
```npx nuxi module add hub```
or
```npm i @nuxthub/core```

**Expected behavior**
Install the package

**Comment by ziadsarour** [comment]
It seems to be related to npmjs or to myself because all packages in npmjs have the same problem.
