### ISSUE TITLE
Adding `@nuxt/content` to nuxt config gives build error

### ISSUE THREAD

**Issue by ra-jeev** [nuxt-hub/core#51]
Just having `@nuxt/content` in `nuxt.config.ts` modules gives the following build error:

```bash
ℹ Initializing prerenderer                                      nitro 11:50:13 PM
ℹ Prerendering 1 routes                                         nitro 11:50:16 PM
  ├─ /api/_content/cache.1712341203899.json (13ms)               nitro 11:50:16 PM
  │ └── Error: [500]
                                                                 nitro 11:50:16 PM
Errors prerendering:
  ├─ /api/_content/cache.1712341203899.json (13ms)               nitro 11:50:16 PM
  │ └── Error: [500]
                                                                 nitro 11:50:16 PM

 ERROR  Exiting due to prerender errors.                               11:50:16 PM

  at prerender (node_modules/nitropack/dist/chunks/prerender.mjs:218:11)
  at async node_modules/nuxt/dist/index.mjs:3471:7
  at async build (node_modules/nuxt/dist/index.mjs:5001:5)
  at async Object.run (node_modules/nuxi/dist/chunks/build.mjs:95:5)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.9edf0930.mjs:1648:16)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.9edf0930.mjs:1639:11)
  at async runMain$1 (node_modules/nuxi/dist/shared/nuxi.9edf0930.mjs:1777:7)

 ERROR  Exiting due to prerender errors.                               11:50:16 PM

error: script "build" exited with code 1
```

nitropack gives the following error:
```json
{"url":"/api/_content/cache.1712340211114.json","statusCode":500,"statusMessage":"","message":"Missing Cloudflare KV binding (KV)"}
```

Reproduction:
Just use the starter template and add `@nuxt/content` package and include it in the nuxt config file. The same can be checked here: [https://github.com/ra-jeev/test-nuxt-hub-app](https://github.com/ra-jeev/test-nuxt-hub-app)

**Comment by Atinux** [comment]
This should fix your issue @ra-jeev 

https://github.com/nuxt-hub/starter/commit/292e8cfdf52ad6ffe29e87785f6be4fdd673d488

**Comment by ra-jeev** [comment]
Okay, so the issue was with the template and not with the core.

Thanks @Atinux.
